# Generated by Django 2.2.1 on 2019-06-29 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(blank=True, choices=[('A', 'Beginner'), ('I', 'Intermediate'), ('P', 'Professional')], max_length=1)),
                ('firstaccess', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SoloRandom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluated', models.BooleanField(default=False)),
                ('solo', models.CharField(blank=True, max_length=100)),
                ('usesolo', models.BooleanField(default=False)),
                ('rating', models.IntegerField(choices=[(1, 'Terrible'), (2, 'Very bad'), (3, 'Bad'), (4, 'Moderate'), (5, 'Good'), (6, 'Very good'), (7, 'Excellent')], null=True)),
                ('musician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='matchmaker.Musician')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SoloAllRules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluated', models.BooleanField(default=False)),
                ('solo', models.CharField(blank=True, max_length=100)),
                ('usesolo', models.BooleanField(default=False)),
                ('rating', models.IntegerField(choices=[(1, 'Terrible'), (2, 'Very bad'), (3, 'Bad'), (4, 'Moderate'), (5, 'Good'), (6, 'Very good'), (7, 'Excellent')], null=True)),
                ('musician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='matchmaker.Musician')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
